### ISSUE TITLE
Euro belongs here?

### ISSUE THREAD

**Issue by PallHaraldsson** [timmyfaraday/AdditionalUnits.jl#1]
Hi, I noticed this package just added.

With just two units added, it's not a lot, was there a reason to not just make a PR to Unitful.jl? I guess you plan for more? Still about discoverability and where stuff should belong, the euro seemed out of place.

FYI: There is https://github.com/JuliaFinance/Currencies.jl/issues/91 and archived https://github.com/bhgomes/UnitfulCurrency.jl

**Comment by timmyfaraday** [comment]
Hi,

Thank you for your remark and interest!
The intend is indeed to add a lot more, specifically more in the context of energy systems.
I propose to add a disclaimer to point to more appropriate packages for specific subclasses, e.g., currencies.

With kind regards,

Tom
